'' Compra de Produto

@startuml
actor Cliente

boundary "Tela de Compra" as Tela
control "PedidoController" as Controller
control "PedidoService" as Service
entity "Pedido" as Pedido
entity "Estoque" as Estoque

Cliente -> Tela : selecionaProduto(produto, quantidade)
Tela -> Controller : realizarCompra(produto, quantidade)
Controller -> Service : verificarEstoque(produto, quantidade)
Service -> Estoque : consultarQuantidade(produto)
Estoque --> Service : quantidadeDisponivel

Controller -> Service : criarPedido(produto, quantidade)
Service -> Pedido : <<create>>
Service -> Estoque : atualizarQuantidade(produto, quantidade)
Service --> Controller : compraConfirmada
Controller -> Tela : exibirConfirmacaoPedido()
Tela -> Cliente : compraRealizada()

@enduml
